Feature: Nlmf_Location EventSubscription + CancelLocation (TS 29.572 §5.2.3 / §5.2.2.5)
  As an LCS consumer (internal NF or AF)
  I want to manage location event subscriptions with the LMF
  So that I receive pushed LocationNotification callbacks for periodic or area-of-interest events
  without polling DetermineLocation myself

  # spec_ref: TS 29.572 §5.2.3.2  (EventSubscription Create  — POST /subscriptions → 201)
  # spec_ref: TS 29.572 §5.2.3.3  (EventSubscription Get     — GET  /subscriptions/{subId} → 200)
  # spec_ref: TS 29.572 §5.2.3.4  (EventSubscription Delete  — DELETE /subscriptions/{subId} → 204)
  # spec_ref: TS 29.572 §5.2.2.5  (CancelLocation one-shot  — POST …/cancel-loc → 204)
  # spec_ref: TS 29.572 §6.1.6.2.4 (LocationNotification body schema)
  # spec_ref: TS 23.273 §7.2 step B2 (deferred location subscription use case)
  # spec_ref: TS 29.571 §5.2       (common SBI types — subscriptions and notifications)
  # spec_ref: TS 29.500 §5.2.4 / TS 29.571 §5.2.7 (ProblemDetails / cause strings)
  # endpoint: POST /nlmf-loc/v1/subscriptions → 201 + Location header
  # endpoint: GET  /nlmf-loc/v1/subscriptions/{subId} → 200 subscription resource
  # endpoint: DELETE /nlmf-loc/v1/subscriptions/{subId} → 204
  # endpoint: POST /nlmf-loc/v1/ue-contexts/{ueContextId}/cancel-loc → 204

  Background:
    Given a clean LMF instance is running on SBI port 8012
    And the LMF has registered with nfType "LMF" and service "nlmf-loc" in the NRF
    And a mock AMF is available for Namf_Location ProvideLocationInfo
    And a mock notification sink server is running to receive LocationNotification callbacks

  # ---------------------------------------------------------------------------
  # Scenario 1 — Happy path: create PERIODIC_REPORTING subscription
  # TS 29.572 §5.2.3.2 — POST /subscriptions → 201 + Location header + subId
  # TS 29.571 §5.2 — subId is a ULID generated by the LMF and echoed in the body
  # ---------------------------------------------------------------------------
  Scenario: Create periodic subscription returns 201 with subId and Location header
    Given the mock AMF returns a Namf LocationData with nrCellId "000000010" and tai plmnId mcc "001" mnc "01" tac "0001" for ueContextId "imsi-001010000000001"
    When an LCS consumer POSTs a subscription with ueContextId "imsi-001010000000001" supi "imsi-001010000000001" eventTrigger "PERIODIC_REPORTING" reportingInterval 2 and notificationUri pointing to the mock sink
    Then the LMF responds with HTTP status 201
    And the response Location header matches "/nlmf-loc/v1/subscriptions/"
    And the response body contains a non-empty subId
    And the response body contains ueContextId "imsi-001010000000001"
    And the response body contains eventTrigger "PERIODIC_REPORTING"

  # ---------------------------------------------------------------------------
  # Scenario 2 — Periodic notification fires: mock sink receives LocationNotification
  # TS 29.572 §6.1.6.2.4 — notification body: subId + notificationItems[].locationData
  # locationData: locationEstimate POINT with lat/lon + nrCellId + tai
  # reportingInterval = 2 s; sink must receive ≥1 notification within 5 s (interval + slack)
  # ---------------------------------------------------------------------------
  Scenario: Periodic subscription fires a LocationNotification at the configured interval
    Given the mock AMF returns a Namf LocationData with nrCellId "000000010" and tai plmnId mcc "001" mnc "01" tac "0001" for ueContextId "imsi-001010000000001"
    When an LCS consumer POSTs a subscription with ueContextId "imsi-001010000000001" supi "imsi-001010000000001" eventTrigger "PERIODIC_REPORTING" reportingInterval 2 and notificationUri pointing to the mock sink
    Then the LMF responds with HTTP status 201
    And the mock sink receives at least 1 LocationNotification within 5 seconds
    And each received notification body contains a non-empty subId
    And each received notification body contains notificationItems with locationData locationEstimate shape "POINT"
    And each received notification body contains notificationItems with locationData nrCellId "000000010"
    And each received notification body contains notificationItems with locationData tai tac "0001"

  # ---------------------------------------------------------------------------
  # Scenario 3 — Happy path: create AREA_OF_INTEREST subscription
  # TS 29.572 §5.2.3.2 — AOI polygon of WGS84 vertices → 201 + subId
  # TS 29.572 §6.1.6.2.2 — areaOfInterest: {polygon: [{lat,lon}…]} ≥3 vertices
  # ---------------------------------------------------------------------------
  Scenario: Create area-of-interest subscription with a WGS84 polygon returns 201 with subId
    When an LCS consumer POSTs a subscription with ueContextId "imsi-001010000000001" supi "imsi-001010000000001" eventTrigger "AREA_OF_INTEREST" polygon vertices "40.3,−3.8 40.5,−3.8 40.5,−3.6 40.3,−3.6" and notificationUri pointing to the mock sink
    Then the LMF responds with HTTP status 201
    And the response Location header matches "/nlmf-loc/v1/subscriptions/"
    And the response body contains a non-empty subId
    And the response body contains eventTrigger "AREA_OF_INTEREST"
    And the response body echoes the areaOfInterest polygon with 4 vertices

  # ---------------------------------------------------------------------------
  # Scenario 4 — AOI notification fires only on boundary crossing, not while stationary
  # TS 29.572 §5.2.3 — notification posted on AREA_ENTERING / AREA_LEAVING transitions only
  # TS 23.273 §7.2 step B2 — LMF samples position via synthetic mobility model
  # Drives the UE outside the polygon, then inside, then stays inside: expects exactly
  # one AREA_ENTERING notification and no spurious notifications while stationary inside.
  # ---------------------------------------------------------------------------
  Scenario: AOI subscription fires exactly once on boundary crossing and is silent while UE is stationary inside
    Given the mock AMF returns a scripted sequence of LocationData positions for ueContextId "imsi-001010000000001":
      | lat     | lon    | description        |
      | 40.2000 | -3.700 | outside polygon    |
      | 40.4168 | -3.703 | entering polygon   |
      | 40.4200 | -3.702 | stationary inside  |
      | 40.4210 | -3.701 | stationary inside  |
    When an LCS consumer POSTs a subscription with ueContextId "imsi-001010000000001" supi "imsi-001010000000001" eventTrigger "AREA_OF_INTEREST" polygon vertices "40.3,−3.8 40.5,−3.8 40.5,−3.6 40.3,−3.6" samplingInterval 1 and notificationUri pointing to the mock sink
    Then the LMF responds with HTTP status 201
    And the mock sink receives exactly 1 LocationNotification within 8 seconds
    And the received notification areaEventInfo event is "AREA_ENTERING"
    And the received notification body contains notificationItems with locationData locationEstimate shape "POINT"

  # ---------------------------------------------------------------------------
  # Scenario 5 — GET subscription status returns 200 with current fields
  # TS 29.572 §5.2.3.3 — GET /subscriptions/{subId} → 200 subscription resource
  # Resource includes: subId, ueContextId, eventTrigger, lastNotified, state fields
  # ---------------------------------------------------------------------------
  Scenario: GET subscription status returns 200 with the subscription resource
    Given the mock AMF returns a Namf LocationData with nrCellId "000000010" and tai plmnId mcc "001" mnc "01" tac "0001" for ueContextId "imsi-001010000000001"
    And an LCS consumer has created a subscription with ueContextId "imsi-001010000000001" supi "imsi-001010000000001" eventTrigger "PERIODIC_REPORTING" reportingInterval 2 and notificationUri pointing to the mock sink
    When an LCS consumer GETs the subscription resource at the returned subId
    Then the LMF responds with HTTP status 200
    And the response body contains the same subId as the created subscription
    And the response body contains ueContextId "imsi-001010000000001"
    And the response body contains eventTrigger "PERIODIC_REPORTING"
    And the response body contains a non-null created timestamp

  # ---------------------------------------------------------------------------
  # Scenario 6 — DELETE subscription (cancel): 204 and no further notifications
  # TS 29.572 §5.2.3.4 / §5.2.2.5 — DELETE → 204; goroutine stopped; sink is silent
  # After delete the sink must receive no further notifications within 2 × interval
  # ---------------------------------------------------------------------------
  Scenario: Cancelling a subscription with DELETE stops further notifications
    Given the mock AMF returns a Namf LocationData with nrCellId "000000010" and tai plmnId mcc "001" mnc "01" tac "0001" for ueContextId "imsi-001010000000001"
    And an LCS consumer has created a subscription with ueContextId "imsi-001010000000001" supi "imsi-001010000000001" eventTrigger "PERIODIC_REPORTING" reportingInterval 2 and notificationUri pointing to the mock sink
    And the mock sink has received at least 1 LocationNotification
    When an LCS consumer DELETEs the subscription at the returned subId
    Then the LMF responds with HTTP status 204
    And the mock sink receives no further LocationNotification within 5 seconds after the delete

  # ---------------------------------------------------------------------------
  # Scenario 7 — One-shot CancelLocation: POST …/cancel-loc returns 204
  # TS 29.572 §5.2.2.5 — abort an in-progress DetermineLocation request context
  # CancelLocation for a UE with no in-progress one-shot is a 204 idempotent no-op
  # ---------------------------------------------------------------------------
  Scenario: One-shot CancelLocation for a UE with no in-progress request returns 204 idempotent no-op
    When an LCS consumer POSTs a CancelLocation for ueContextId "imsi-001010000000001"
    Then the LMF responds with HTTP status 204

  # ---------------------------------------------------------------------------
  # Scenario 8 — Error: create without notificationUri → 400 MANDATORY_IE_MISSING
  # TS 29.572 §5.2.3.2 / TS 29.571 §5.2.7 — notificationUri is mandatory;
  # LMF must reject before starting a goroutine or inserting into the registry
  # ---------------------------------------------------------------------------
  Scenario: Create subscription without notificationUri is rejected with 400 MANDATORY_IE_MISSING
    When an LCS consumer POSTs a subscription with ueContextId "imsi-001010000000001" supi "imsi-001010000000001" eventTrigger "PERIODIC_REPORTING" and no notificationUri
    Then the LMF responds with HTTP status 400
    And the response ProblemDetails cause is "MANDATORY_IE_MISSING"
    And the metric fivegc_lmf_subscription_create_total with label result "REJECT" is incremented

  # ---------------------------------------------------------------------------
  # Scenario 9 — Error: GET unknown subId → 404 SUBSCRIPTION_NOT_FOUND
  # Error: DELETE unknown subId → 404 SUBSCRIPTION_NOT_FOUND
  # TS 29.572 §5.2.3.3 / §5.2.3.4 — look-up in registry fails → 404
  # [VERIFY: cause enum: SUBSCRIPTION_NOT_FOUND vs generic NOT_FOUND — TS 29.572 YAML]
  # ---------------------------------------------------------------------------
  Scenario: GET on an unknown subscription subId returns 404 SUBSCRIPTION_NOT_FOUND
    When an LCS consumer GETs the subscription resource at subId "01NONEXISTENT0000000000000"
    Then the LMF responds with HTTP status 404
    And the response ProblemDetails cause is "SUBSCRIPTION_NOT_FOUND"

  Scenario: DELETE on an unknown subscription subId returns 404 SUBSCRIPTION_NOT_FOUND
    When an LCS consumer DELETEs the subscription at subId "01NONEXISTENT0000000000000"
    Then the LMF responds with HTTP status 404
    And the response ProblemDetails cause is "SUBSCRIPTION_NOT_FOUND"

  # ---------------------------------------------------------------------------
  # Scenario 10 — Error: create AOI with degenerate polygon (<3 vertices) → 400
  # TS 29.572 §6.1.6.2.2 — polygon must have ≥3 vertices; fewer → degenerate area
  # Error table: polygon with <3 vertices → MANDATORY_IE_MISSING (degenerate area)
  # ---------------------------------------------------------------------------
  Scenario: Create AOI subscription with a degenerate polygon is rejected with 400 MANDATORY_IE_MISSING
    When an LCS consumer POSTs a subscription with ueContextId "imsi-001010000000001" supi "imsi-001010000000001" eventTrigger "AREA_OF_INTEREST" polygon vertices "40.3,−3.8 40.5,−3.8" and notificationUri pointing to the mock sink
    Then the LMF responds with HTTP status 400
    And the response ProblemDetails cause is "MANDATORY_IE_MISSING"

  # ---------------------------------------------------------------------------
  # Scenario 11 — Error: create with unknown eventTrigger → 400 INVALID_MSG_FORMAT
  # TS 29.572 §5.2.3.2 — eventTrigger must be PERIODIC_REPORTING | AREA_OF_INTEREST
  # Error table: unknown trigger value → INVALID_MSG_FORMAT
  # ---------------------------------------------------------------------------
  Scenario: Create subscription with an unknown eventTrigger is rejected with 400 INVALID_MSG_FORMAT
    When an LCS consumer POSTs a subscription with ueContextId "imsi-001010000000001" supi "imsi-001010000000001" eventTrigger "CONTINUOUS_STREAMING" and notificationUri pointing to the mock sink
    Then the LMF responds with HTTP status 400
    And the response ProblemDetails cause is "INVALID_MSG_FORMAT"
