global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 5gc-nfs
    static_configs:
      - targets: [nrf:9100]
        labels: {nf: NRF}
      - targets: [amf:9101]
        labels: {nf: AMF}
      - targets: [ausf:9102]
        labels: {nf: AUSF}
      - targets: [udm:9103]
        labels: {nf: UDM}
      - targets: [udr:9104]
        labels: {nf: UDR}
      - targets: [smf:9105]
        labels: {nf: SMF}
      - targets: [pcf:9106]
        labels: {nf: PCF}
      - targets: [upf:9107]
        labels: {nf: UPF}
      - targets: [nssf:9109]
        labels: {nf: NSSF}
      - targets: [smsf:9110]
        labels: {nf: SMSF}
      - targets: [bsf:9111]
        labels: {nf: BSF}
      - targets: [nef:9112]
        labels: {nf: NEF}
      - targets: [lmf:9113]
        labels: {nf: LMF}
