dnns:
    - gateway_ip: 172.30.6.1
      name: internet
      tun_addr: 10.60.0.254/24
      tun_name: upfgtp0
      ue_ip_pool: 10.60.0.0/24
    - gateway_ip: 172.30.7.1
      name: ims
      tun_addr: 10.61.0.254/24
      tun_name: upfgtp1
      ue_ip_pool: 10.61.0.0/24
    - gateway_ip: 172.30.8.1
      name: gaming
      tun_addr: 10.62.0.254/24
      tun_name: upfgtp2
      ue_ip_pool: 10.62.0.0/24
    - gateway_ip: 172.30.9.1
      name: gold
      tun_addr: 10.63.0.254/24
      tun_name: upfgtp3
      ue_ip_pool: 10.63.0.0/24
metrics:
    address: 0.0.0.0:9107
n3:
    address: 0.0.0.0:2152
    ip: 172.30.3.100
n4:
    address: 0.0.0.0:8805
nf_instance_id: 00000000-0000-4005-8000-000000000001
